src/Entity/Personne.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PersonneRepository")
 * @UniqueEntity(
 * fields={"nom", "Prenom"},
 * message="Le personnage existe déjà"
 * )
 */
class Personne
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $faction;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getFaction(): ?string
    {
        return $this->faction;
    }

    public function setFaction(string $faction): self
    {
        $this->faction = $faction;

        return $this;
    }
}

src/Form/PersonneType.php
<?php

namespace App\Form;

use App\Entity\Faction;
use App\Entity\Personne;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('Prenom')
            ->add('faction', ChoiceType::class, [
            'choices' =>[
                'Choisir les Jedi' => 'Jedi',
                'Choisir les Sith' => 'Sith'
            ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Personne::class,
        ]);
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Personne;
use App\Form\PersonneType;
use App\Repository\PersonneRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

class AccueilController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function index(PersonneRepository $personneRepository)
    {
        $personnageJedi = $personneRepository->findby(["faction" => "Jedi"]);
        $personnageSith = $personneRepository->findby(["faction" => "Sith"]);

        return $this->render('accueil/index.html.twig', [
            "personnageJedi" => $personnageJedi,
            "personnageSith" => $personnageSith,
        ]);
    }

        /**
     * @Route("/listePerso", name="listePerso")
     */
    public function listePerso(PersonneRepository $personneRepository, PaginatorInterface $paginatorInterface, Request $request)
    {
        $personnage = $personneRepository->findAll();

        $personnage = $paginatorInterface->paginate(
            $personneRepository->findAllWithPagination(),
            $request->query->getInt('page', 1), /*page number*/
            8 /*limit per page*/
        );

        return $this->render('accueil/listePerso.html.twig', [
            "personnage" => $personnage,
        ]);
    }

            /**
     * @Route("/listePerso/personnage/creation", name="inscription")
     * @Route("/listePerso/personnage/{id}", name="modification", methods="GET|POST")
     */
    public function inscription(Personne $personnage = null, Request $request, EntityManagerInterface $entityManagerInterface)
    {
        if (!$personnage) {
            $personnage = new Personne;
        }
        
        $form = $this->createForm(PersonneType::class, $personnage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $modif = $personnage->getId() !== null;
            $entityManagerInterface->persist($personnage);
            $entityManagerInterface->flush();
            $this->addFlash("success", ($modif) ? "La modification a été effectuée" : "L'ajout a été effetuée");
            return $this->redirectToRoute("listePerso");
        }

        return $this->render('accueil/inscription.html.twig', [
            "personnage" => $personnage,
            "form"=>$form->createView(),
            "isModification" => $personnage->getId() !== null,
        ]);
    }

               /**
     * @Route("/listePerso/personnage/{id}", name="suppPersonnage", methods="SUP")
     */
    public function suppression(Personne $personnage, Request $request, EntityManagerInterface $entityManagerInterface)
    {
        if ($this->isCsrfTokenValid("SUP".$personnage->getId(), $request->get("_token"))) {
            $entityManagerInterface->remove($personnage);
            $entityManagerInterface->flush();
            $this->addFlash('success', "La suppression a été effectué");
            return $this->redirectToRoute("listePerso");
        }
    }
}

templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}



<div class="masthead">

<div class="container">
    <div class="jumbotron">
    <h1 class="display-3">Jedi ou Sith ?</h1>
    <p class="lead">Choisissez votre camp</p>
    <hr class="my-4">
    <p>Il y a actuellement {{personnageJedi|length}} Jedi et {{personnageSith|length}} Sith</p>
    <p class="lead">
      <a class="btn btn-success btn-lg" href="{{path('inscription')}}" role="button">Créer un Personnage</a>
    </p>
    <p class="lead">
      <a class="btn btn-info btn-lg" href="{{path('listePerso')}}" role="button">Liste des Personnages</a>
    </p>
  </div>
</div>
</div>

{% endblock %}

templates/accueil/inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}


<div class="masthead">
    <div class="container">
        <div class="jumbotron">    
            {% if isModification %}
                Modification de {{ personnage.prenom }} {{ personnage.nom }} 
            {% else %}
                Ajout d'un Personnage 
            {% endif %}
            {{ form_start(form) }}
                {{form_widget(form)}}
                <input type="submit" class="btn btn-success" value="valider">
            {{ form_end(form) }}
        </br>
      </div>
    </div>
    </div>

{% endblock %}

templates/accueil/listePerso.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des personnages{% endblock %}

{% block body %}
{% for message in app.flashes('success') %}
<div class="alert alert-success">{{message}}</div>
{% endfor %}

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">Prenom</th>
        <th scope="col">Faction</th>
        <th scope="col">Modifier</th>
        <th scope="col">Supprimer</th>
      </tr>
    </thead>
    <tbody>
 
{% for personnage in personnage %}
      <tr>
        <td>{{personnage.nom}}</td>
        <td>{{personnage.prenom}}</td>
        <td>{{personnage.faction}}</td>
        <td><a href="{{path('modification', {'id' : personnage.id})}}" class="btn btn-danger">Modifier</a></td>
        <td>
          <form method="POST" style="display:inline-block" action="{{path('suppPersonnage', {'id' : personnage.id})}}" onsubmit="return confirm('Confirmer la suppression ?')">
          <input type="hidden" name="_method" value="SUP">
          <input type="hidden" name="_token" value="{{csrf_token('SUP' ~ personnage.id)}}">
          <input type="submit" class="btn btn-primary" value="Supprimer">
          </form>
        </td>
      </tr>
{% endfor %}

    </tbody>
  </table> 

<div class="navigation">
    {{ knp_pagination_render(personnage) }}
</div>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Jedi or Sith{% endblock %}</title>
        <link rel="stylesheet" href="https://bootswatch.com/4/journal/bootstrap.min.css">
        <link rel="stylesheet" href="{{asset('css/main.css')}}">
        {% block stylesheets %}{% endblock %}
    </head>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{path('accueil')}}">Jedi Or Sith</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{path('accueil')}}">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{path('listePerso')}}">Liste des personnages</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{path('inscription')}}">Créer un personnage</a>
            </li>
          </ul>
        </div>
      </nav>

    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>